# Appendix    

## Do's and Don'ts  

Below we provide some tips for what to do and what not to do when you build machine learning models.  

### Do's  

* Do consider whether the data is appropriate for your research questions. 
* Do data exploratory analysis before jumping into analysis. Look at summary statistics and make plots to familiarize yourself with the data. 
* Document the process with reasonable details, so you or other researchers can reproduce the study if needed. 
* Along the same line, if you write scripts for your code, add comments along the way. 
* In the publication, explain what the result entails and the limitations of the model. 
* When possible, use interpretable and/or parsimonious models. Think Occam's razor. 
* Make data and code available to others if possible. 
* 


### Don'ts  

* Don't alter the raw data. Use a script to process data instead. 
* Don't over interpret the result. For example, if the samples all come from one geographic area, you might not be able to generalize the result to other areas.  
* 
